global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'thoughts-backend-render'
    metrics_path: '/actuator/prometheus'
    scheme: https
    static_configs:
      - targets: ['thought-0hcs.onrender.com']
